fcsc_mobile_manipulator:
 joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

 arm_with_slider_joint_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
   - slider_joint
   - joint1
   - joint2
   - joint3
   - joint4
   - joint5
   - joint6
   
  constraints:
   goal_time: 30
   slider_joint:
    goal: 1
   joint1:
    goal: 1
   joint2:
    goal: 1
   joint3:
    goal: 1
   joint4:
    goal: 1
   joint5:
    goal: 1
   joint6:
    goal: 1
   stop_trajectory_duration: 30
   
  gains:
   slider_joint: {p: 7500.0, i: 0.01, d: 500.0}
   joint1: {p: 10000.0, i: 0.01, d: 700.0}
   joint2: {p: 7500.0, i: 0.01, d: 500.0}
   joint3: {p: 7500.0, i: 0.01, d: 500.0}
   joint4: {p: 7500.0, i: 0.01, d: 500.0}
   joint5: {p: 100.0, i: 0.01, d: 10.0}
   joint6: {p: 7500.0, i: 0.01, d: 500.0}

 gripper_joint_controller:
  type: "effort_controllers/GripperActionController"
  joint: gripper_joint
  gains:
   gripper_joint: {p: 10.0, i: 0.1, d: 10.0}
 

